---
  
  - include_tasks: requirements.yml

  - include_tasks: mongodb.yml
    when: rocket_chat_include_mongodb|bool
    tags: mongodb

  - include_tasks: install_rocketchat.yml
    when: rocket_chat_include_install_rocketchat|bool
    tags: install_rocketchat

  - ingclude_tasks: nginx.yml
    when: rocket_chat_include_nginx|bool
    tags: nginx

  - include_tasks: letsencrypt.yml
    when: rocket_chat_include_letsencrypt|bool
    tags: letsencrypt

