---
# handlers/main.yml: Handlers for RocketChat.Ansible
  - name: Reload the Nginx service
    service:
      name: nginx
      state: reloaded
      enabled: yes

  - name: Restart the MongoDB service
    service:
      name: mongod
      state: restarted

  - name: Upgrade Rocket.Chat
    include: upgrade.yml
    when: rocket_chat_deploy_state.stat.exists
    tags: upgrade

  - name: Update the Rocket.Chat service configuration
    systemd:
      daemon_reload: yes
    when: ansible_service_mgr == 'systemd'

  - name: Reload nginx systemd
    systemd:
      name: nginx
      state: reloaded
      enabled: yes

  - name: Restart the Rocket.Chat service
    service:
      name: rocketchat
      state: restarted

  - name: Ensure APT cache has been updated recently
    apt:
      update_cache: yes
      #cache_valid_time: 3600
    when: ansible_pkg_mgr == "apt"
